In [1]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import MinMaxScaler
import pandas as pd
import numpy as np

In [2]:
dataset = pd.read_csv('data/milk.csv')
train_data = np.array(dataset)[:, 1:-1]
train_label = np.array(dataset)[:, -1]
print(train_data)
print(train_label)

[[35 1 0 1 0 254]
 [36 0 1 0 1 253]
 [70 1 1 1 1 246]
 ...
 [40 1 1 1 1 255]
 [43 1 0 1 0 250]
 [55 0 1 1 1 255]]
['high' 'high' 'low' ... 'low' 'high' 'low']


In [3]:
sc = MinMaxScaler(feature_range=(0, 1))
data = sc.fit_transform(train_data)
print(data)


[[0.01785714 1.         0.         1.         0.         0.93333333]
 [0.03571429 0.         1.         0.         1.         0.86666667]
 [0.64285714 1.         1.         1.         1.         0.4       ]
 ...
 [0.10714286 1.         1.         1.         1.         1.        ]
 [0.16071429 1.         0.         1.         0.         0.66666667]
 [0.375      0.         1.         1.         1.         1.        ]]


In [5]:
kNN = KNeighborsClassifier(n_neighbors=3, weights='distance')
kNN.fit(train_data, train_label)

temperature = input('Masukkan Temperature: ')
taste = input('Masukkan Taste: ')
odor = input('Masukkan Odor: ')
fat = input('Masukkan Fat: ')
turbidity = input('Masukkan Turbidity: ')
color = input('Masukkan Colour: ')
test_data = np.array([int(temperature), int(taste), int(odor), int(fat), int(turbidity), int(color)])
test_data=np.reshape(test_data,(1,-1))
print(test_data)
hasil=kNN.predict(test_data)
print("Hasil dari k-NN : ",hasil)

[[ 34   1   1   0   0 248]]
Hasil dari k-NN :  ['medium']
