In [4]:
from sklearn.preprocessing import MinMaxScaler
import pandas as pd
import numpy as np

In [5]:
dataset = pd.read_csv('data/milk_training.csv')
train_data = np.array(dataset)[:, 1:-1]
train_label = np.array(dataset)[:, -1]
print(train_data)
print(train_label)

[[35 1 0 1 0 254]
 [36 0 1 0 1 253]
 [37 1 1 1 1 255]
 ...
 [41 1 0 0 0 247]
 [41 0 0 0 0 255]
 [38 0 0 0 0 255]]
['high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
 'high' 'high' 'high' 'high' 'high

In [6]:
sc = MinMaxScaler(feature_range=(0, 1))
data = sc.fit_transform(train_data)
print(data)

[[0.01785714 1.         0.         1.         0.         0.93333333]
 [0.03571429 0.         1.         0.         1.         0.86666667]
 [0.05357143 1.         1.         1.         1.         1.        ]
 ...
 [0.125      1.         0.         0.         0.         0.46666667]
 [0.125      0.         0.         0.         0.         1.        ]
 [0.07142857 0.         0.         0.         0.         1.        ]]
