In [1]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import MinMaxScaler
import pandas as pd
import numpy as np

In [2]:
dataset = pd.read_csv('data/milk_testing.csv')
train_data = np.array(dataset)[:, 1:-1]
train_label = np.array(dataset)[:, -1]
print(train_data)
print(train_label)

[[45 1 1 1 0 245]
 [37 1 1 1 1 255]
 [38 1 0 1 0 255]
 ...
 [37 0 0 0 0 255]
 [40 1 0 0 0 250]
 [45 1 1 0 0 247]]
['high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
 'high' 'high' 'high' 'high' 'high' 'high' 'high' 'low' 'low' 'low' 'low'
 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low'
 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low'
 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low'
 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low'
 'low' 'low' 'low' 'low

In [3]:
sc = MinMaxScaler(feature_range=(0, 1))
data = sc.fit_transform(train_data)
print(data)

[[0.19642857 1.         1.         1.         0.         0.33333333]
 [0.05357143 1.         1.         1.         1.         1.        ]
 [0.07142857 1.         0.         1.         0.         1.        ]
 ...
 [0.05357143 0.         0.         0.         0.         1.        ]
 [0.10714286 1.         0.         0.         0.         0.66666667]
 [0.19642857 1.         1.         0.         0.         0.46666667]]


In [4]:
kNN = KNeighborsClassifier(n_neighbors=3, weights='distance')
kNN.fit(train_data, train_label)

temperature = input('Masukkan Temperature: ')
taste = input('Masukkan Taste: ')
odor = input('Masukkan Odor: ')
fat = input('Masukkan Fat: ')
turbidity = input('Masukkan Turbidity: ')
color = input('Masukkan Colour: ')
test_data = np.array([int(temperature), int(taste), int(odor), int(fat), int(turbidity), int(color)])
test_data=np.reshape(test_data,(1,-1))
print(test_data)
hasil=kNN.predict(test_data)
print("Hasil dari k-NN : ",hasil)

[[ 40   1   1   0   0 240]]
Hasil dari k-NN :  ['medium']
